=== ENSTABretagneRobotics/File_conversions/NMEA2XML_WRSC2015/AreaScanningResult.xsd
<?xml version="1.0" encoding="utf-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
xmlns:gml="http://www.opengis.net/gml"
attributeFormDefault="unqualified" elementFormDefault="qualified">
  <xs:import namespace="http://www.opengis.net/gml" schemaLocation="http://schemas.opengis.net/gml/3.1.1/base/gml.xsd" />
  <xs:element name="AreaScanning" type="TeamType"/>
  <xs:complexType name="TeamType">
    <xs:sequence>
      <xs:element name="TeamName" type="xs:string"/>
      <xs:element name="Section" maxOccurs="100">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="sectioni" type="xs:integer" />
            <xs:element name="sectionj" type="xs:integer" />
            <xs:element name="dateTime" type="xs:dateTime" />
            <xs:element ref="gml:pos"></xs:element>
            <xs:element name="depth" type="xs:float" minOccurs="0" />
            <xs:element name="watertemp" type="xs:float" minOccurs="0" />
            <xs:element name="airtemp" type="xs:float" minOccurs="0" />
            <xs:element name="watersalinity" type="xs:float" minOccurs="0" />
            <xs:element name="conductivity" type="xs:float" minOccurs="0" />
            <xs:element name="chlorophyll" type="xs:float" minOccurs="0" />
            <xs:element name="ammonium" type="xs:float" minOccurs="0" />
            <xs:element name="nitrate" type="xs:float" minOccurs="0" />
            <xs:element name="chloride" type="xs:float" minOccurs="0" />
            <xs:element name="totaldissolvedsolids" type="xs:float" minOccurs="0" />
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
    <xs:attribute name="Teamid" type="xs:string" use="required"/>
  </xs:complexType>
</xs:schema>

=== ENSTABretagneRobotics/File_conversions/NMEA2XML_WRSC2015/sample.xml
<?xml version="1.0" encoding="utf-8"?>
<AreaScanning Teamid="" xmlns:gml="http://www.opengis.net/gml" xmlns:smil20="http://www.w3.org/2001/SMIL20/" xmlns:smil20lang="http://www.w3.org/2001/SMIL20/Language" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xml="http://www.w3.org/XML/1998/namespace" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="AreaScanningResult.xsd">
  <TeamName>TeamName</TeamName>
  <Section>
    <sectioni>0</sectioni>
    <sectionj>0</sectionj>
    <dateTime>2001-12-31T12:00:00Z</dateTime>
    <gml:pos srsDimension="2" srsName="urn:ogc:def:crs:EPSG:6.6:4326">49.27 -123.11</gml:pos>
    <depth>0.0</depth>
    <watertemp>0.0</watertemp>
    <airtemp>0.0</airtemp>
    <watersalinity>0.0</watersalinity>
    <conductivity>0.0</conductivity>
    <chlorophyll>0.0</chlorophyll>
    <ammonium>0.0</ammonium>
    <nitrate>0.0</nitrate>
    <chloride>0.0</chloride>
    <totaldissolvedsolids>0.0</totaldissolvedsolids>
  </Section>
  <Section>
    <sectioni>1</sectioni>
    <sectionj>0</sectionj>
    <dateTime>2001-12-31T12:00:10Z</dateTime>
    <gml:pos srsDimension="2" srsName="urn:ogc:def:crs:EPSG:6.6:4326">49.27546 -123.11</gml:pos>
    <depth>0.0</depth>
    <watertemp>0.0</watertemp>
    <airtemp>0.0</airtemp>
    <watersalinity>0.0</watersalinity>
    <conductivity>0.0</conductivity>
    <chlorophyll>0.0</chlorophyll>
    <ammonium>0.0</ammonium>
    <nitrate>0.0</nitrate>
    <chloride>0.0</chloride>
    <totaldissolvedsolids>0.0</totaldissolvedsolids>
  </Section>
</AreaScanning>
